### ISSUE TITLE
calico cni ipam on coreos baremetal selfhosted 

### ISSUE THREAD

**Issue by maikotz** [projectcalico/cni-plugin#246]
Hi, 

this is rather a question than a bug, I'm just not quite sure who else to ask, so I thought here would be the right place. 

I've got my self-hosted kubernetes cluster running and wanted to update calico to 1.0.0 and enable calico networking with cni and policy controller. As soon as I started everything, my apiserver and kubedns became unreachable and the service was unreachable.
My pods get calico pool Ip's as expected in 192.160.0.0/16 but I thought that the self-hosted apiserver and kubedns at 10.100.0.1 and 10.100.0.2 would still be available. 

Since this is just a testing setup it's not a huge problem but I thought it might save some time to ask here first before deploying the whole cluster from scratch with the new calico version and see if it's a problem of the setup or the late update from CALICO_NETWORKING=NO to YES.

The cluster is running, I updated calico-node and cni plugins, setup a pool and restarted the kubelet-wrapper to find that I cannot reach 10.100.0.1 and therefor my kubedns doesn't come up and my services go down.

After thinking a bit I thought it even makes sense, since calico wants to provide the insulation between pods, so is this intended and I cannot use it with a self-hosted cluster where the kubernetes apiserver itself runs as a pod, or am I supposed to still be able to reach it? 
In that case I would tear down the cluster and start from scratch.

Thanks for any recommendations.

**Comment by caseydavenport** [comment]
@maikotz You should be able to run Calico even when self-hosting the Kubernetes components.  Since they run with host networking, Calico won't enforce network policy on them by default and things should work as usual.

One thing to check would be if pods can talk to each other using their pod IP addresses rather than the service address.  This will isolate whether it's an issue with Calico, or an issue with the kube-proxy that is preventing pods from accessing the API.

**Comment by maikotz** [comment]
Thanks for the point in the right direction! @caseydavenport
