### ISSUE TITLE
cp -n is not a real flag in calico/cni container 

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#261]
The install-cni.sh script does this:
```
cp -n /opt/cni/bin/flannel /host/opt/cni/bin/
```

```
cp: invalid option -- n
BusyBox v1.26.2 (2017-01-12 18:09:33 UTC) multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST

        -a      Same as -dpR
        -R,-r   Recurse
        -d,-P   Preserve symlinks (default if -R)
        -L      Follow all symlinks
        -H      Follow symlinks on command line
        -p      Preserve file attributes if possible
        -f      Overwrite
        -i      Prompt before overwrite
        -l,-s   Create (sym)links
        -u      Copy only newer files
```

**Comment by caseydavenport** [comment]
@tomdee added this to the v2.1.0 milestone since it's a bug in a v2.1.0 feature.

**Comment by pmichali** [comment]
Is there a workaround? I'd like to update cni-plugin with some debug messages to look into IP address creation for veths.

**Comment by gunjan5** [comment]
@pmichali This issue shouldn't be there in the calico/cni:latest docker image since it was never pushed to the `latest` image, but 2 PRs (just merged) should fix it. 
To answer your question, you can check which IP is assigned to the POD by looking at kubectl logs and grep for `"Auto-assign"`, it should look like:
```

Feb 06 23:08:29 node-01 kubelet[12312]: time="2017-02-06T23:08:29Z" level=info msg="Auto-assigned 1 out of 1 IPv4s: [192.168.19.3]"
Feb 06 23:08:29 node-01 kubelet[12312]: Calico CNI IPAM assigned addresses IPv4=[192.168.19.3] IPv6=[]
```
Hope that answers your question.
