### ISSUE TITLE
custome kubeconfig with certs

### ISSUE THREAD

**Issue by talset** [projectcalico/cni-plugin#286]
We are facing to an issue because our calico pods are not able to speak with the kubernetes-api.

For security reason we are using  **--anonymous-auth=false**
```Enables anonymous requests to the secure port of the API server. Requests that are not rejected by another authentication method are treated as anonymous requests. Anonymous requests have a username of system:anonymous, and a group name of system:unauthenticated. (default true)```

It means that each component need to use a kubeconfig containing a certification to be authentified on kubernetes. If not we receive an Unauthorized error.

It seems calico installer is generating and overriding a "simple" kubeconfig (https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L99). 

How do you handle a different kubeconfig for this usecase ?

(maybe linked to https://github.com/projectcalico/calico/issues/578)

Thanks for your answers

**Comment by caseydavenport** [comment]
@talset the installer does try to create its own kubeconfig.  However, you can configure it to use any kubeconfig you'd like.

In the self-hosted manifest `calico.yaml`, you can change this line so that it points at your desired kubeconfig file (as it is, that placeholder is auto-populated with the location of the created kubeconfig file).

e.g 

```
"kubeconfig": "__KUBECONFIG_FILEPATH__"
```

can become

```
"kubeconfig": "/path/to/my/kubeconfig"
```
