### ISSUE TITLE
Incorrect Documentation (or behaviour) in CNI IP annotations

### ISSUE THREAD

**Issue by rikatz** [projectcalico/cni-plugin#288]
I've been testing the IPAM annotations in CNI with Kubernetes, and faced the following.

In docs, about ``cni.projectcalico.org/ipAddrsNoIpam``:

```
cni.projectcalico.org/ipAddrsNoIpam: A list of IPv4 and/or IPv6 addresses to assign to the Pod, bypassing IPAM. Any IP conflicts and routing have to be taken care of manually or by some other system. Calico will only distribute routes to a Pod if its IP address falls within a Calico IP Pool. If you assign an IP address that is not in a Calico IP Pool, you must ensure that routing to that IP address is taken care of through another mechanism.
```

So I've made an annotation in my Deployment (actually at POD Spec) as the following:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: katz1
  resourceVersion: "4811"
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipAddrsNoIpam: '["10.111.5.1","10.111.5.2","10.111.5.3","10.111.5.4"]'
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

But got this error in CNI Log:

```
E0315 22:44:09.505057   17130 cni.go:255] Error adding network: Can not have more than one IPv4 address in ipAddrsNoIpam annotation
E0315 22:44:09.505079   17130 cni.go:209] Error while adding to cni network: Can not have more than one IPv4 address in ipAddrsNoIpam annotation
E0315 22:44:09.505102   17130 docker_manager.go:2196] Failed to setup network for pod "nginx-2554572815-bb598_katz1(03f355a8-09ea-11e7-b02d-525400b47e5d)" using network plugins "cni": Can not have more than one IPv4 address in ipAddrsNoIpam annotation; Skipping pod
```

So, the docs says a list of IPs. Error tells me that I can not do that. Are the docs wrong?

Thanks!

**Comment by rikatz** [comment]
Also about this, Docs are not pretty clear about where I do insert those annotations. It would be great if they could be inserted by namespace (and I allocate something like an IPv6 range for each of my clients), but I don't think this is the case right now.

**Comment by tmjd** [comment]
It was intentional that it is a list but currently only supports one value at this time. See https://github.com/projectcalico/cni-plugin/issues/258#issue-204416440
The docs should make that clear though.

**Comment by gunjan5** [comment]
There is a note in that doc that says `"You can only specify one IPv4/IPv6 or one IPv4 and one IPv6 address with these annotations."`

**Comment by tmjd** [comment]
I'm not very familiar with these features but it looks like the IpAddrs(NoIpam) annotations are for specifying specific ip addresses for a container so it doesn't really make sense to use a range, especially with the NoIpam version.
To do what you are asking couldn't you just create an IP pool and then use the ipv[46]pools annotation?

**Comment by rikatz** [comment]
That's questionable. I would like to specify a range for a deployment, so I do this by configuring this in the POD SPEC Template. As PODs cannot have the same IP Address, my configuration contains a range.

**Comment by tmjd** [comment]
@gunjan5 what do you think about the idea to have a range? It seems misplaced especially with the NoIpam version because that, by name, indicates that the address management is taking place external to calico.
I think a reasonable feature request would be the ability to specify a subset or range using the ipv[46]pools, then calico would be doing IPAM but the annotations would allow influence on a pod level.  (I have no idea how feasible it is or isn't.)

@rikatz I can follow your reasoning on wanting to have an ip range/cidr per namespace too.
Could you share your use case that drives the need for a set of pods to be in a segmented address range?  I can imagine a scenario but I'd like to hear you specific use case.

**Comment by gunjan5** [comment]
@rikatz I understand what you mean by per namespace ipPool, but I'm not sure I understand your comment https://github.com/projectcalico/cni-plugin/issues/288#issuecomment-287162836 . If you look at this section of the docs http://docs.projectcalico.org/v2.1/getting-started/kubernetes/troubleshooting "**How do I configure the Pod IP range?**" that explains the two possible ways to configure CNI to assign IP addresses from a range. You can also specify multiple IPv4 and IPv6 pools there (as a pod annotation **OR** as the CNI config file; example : http://docs.projectcalico.org/v2.1/reference/cni-plugin/configuration#ipam ).

If you are bypassing the IPAM, you can't specify a range since it would require some kind of management which is what IPAM does. 

Let me know if I'm misunderstanding your question.

**Comment by rikatz** [comment]
@gunjan5 @tmjd Let me clarify this.

About the noIP range, @gunjan5 is right! If I bypass the IPAM, how can I request a bunch of ips and check which is in use and which is not.

About the IP per Namespace, I work on a company that deals with all kind of data, some of them sensitive. Although our PaaS that is being built with Kubernetes + Calico uses basically 2 IP pools (one for QA/Validation/DEV apps and other for production only), some of those apps needs special access to unauthenticated resources (like some legacy apps in mainframes, some old Oracle databases, etc).

Our 'security' today between App servers and those resources is based in Inbound Firewall Rules with authentication (some of them enforced by law or regulations). 

I know I can use calico egress rules (and I will), but our security teams, in some cases only open those firewall rules if they know the exactly IP (or an isolated IP Pool) of the App Server.

While using a /16 for the described networks above, those special cases needs a special network (I'm trying the minimal necessary with calico, a /26 IP Pool) for them, to allow us to request those Firewall Rules.

Additionally, I don't wan't my users (from those special cases) to change their IP Pool. This is dangerous for us, like some bad configured deployment using an unwanted IP Pool, or maybe a QA App using a Production IP Pool.

So for me, the simpliest solution is to configure the used IP Pool in the creation of the Namespace (as we do with the DefaultDeny annotation, and with the Limits and Quotas Resources).

Have I clarified this? :)

Thanks guys!

**Comment by tmjd** [comment]
@rikatz Thank you for the clarification.

I think you understand the current features so I do not think there is much that can be done right now except create specific feature requests to enable what you want.  I think the following would enable what you want/need:
- [Link Kubernetes Namespace and Calico IP Pool](https://github.com/projectcalico/k8s-policy/issues/78): be able to specify a link between a Namespace and IP Pool so that a pod in that Namespace will always be pulled from the linked IP Pool.

Are there other features that would be necessary?

**Comment by rikatz** [comment]
@tmjd That's nice :)

I've another feature request regarding the usage of MD5 authentication in Bird / BGP Configuration, but I've seen this here:

https://github.com/projectcalico/calicoctl/issues/1076

Thanks :)

**Comment by tmjd** [comment]
I'm going to close this issue then, if there is additional discussion or features to discuss feel free to reopen.
