### ISSUE TITLE
containernetworking/cni has changed

### ISSUE THREAD

**Issue by timchenxiaoyu** [projectcalico/cni-plugin#344]
containernetworking/cni

Removes the following packages:

ip
ipam
ns
testutils
utils

cann't run cni-plugin with new containernetworking/cni

**Comment by caseydavenport** [comment]
Yeah, a whole bunch of packages have been moved to the `containernetworking/plugins` repo, so we'll need to revendor that in.

For now, it should still build fine because we've got glide.lock pinning the version of `containernetworking/cni` that we use, but we should update our deps to the new repo.
