### ISSUE TITLE
Kubernetes Calico and DNS resolution fails

### ISSUE THREAD

**Issue by brianp9906** [projectcalico/cni-plugin#542]
Using Kubernetes and Calico latest and I found that
dig google.com @10.96.0.10 
Fails on all worker nodes. Works fine on the master. iptables on the worker nodes shows routing it properly with a nat back to the Kube proxy ip. 
I checked Kube dns logs and it looks fine and normal. It just seems to be a routing issue. Why would this be happening? 

All 3 nodes (2 worker 1 master) running RHEL 7.5. 

Thank you.

**Comment by brianp9906** [comment]
I changed to weave instead and it works without issue.

**Comment by tmjd** [comment]
Where were you deploying? AWS, GCE, bare-metal, OpenStack?  If in one of the clouds I'm wondering if you needed some rules to allow IP-in-IP traffic for cross node traffic to work.

**Comment by brianp9906** [comment]
No just using RedHat 7 with 3 servers in the same subnet.

**Comment by tmjd** [comment]
If it is a pod routing issue you could run `calicoctl node status` on  the nodes and check that the BGP connections are being established.

**Comment by comphilip** [comment]
@tmjd You are awesome.

I have no idea about calico CNI plugin. I setup two K8S cluster with luck.
Today I reset a cluster while DNS and kube proxy not work. There is no error log.

With `calicoctl node status`, I finally found where the problem is. Worker node use wrong network interface and not connect to master node.

So I change IP_AUTODETECTION_METHOD option to make calico use the correct network interface. Everything works well.

**Comment by yudaykiran** [comment]
I am having a similar issue, but this is on IBM Cloud Private(ICP) running on Azure. ICP uses calico as their default CNI plugin. The cluster was brought up using the following terraform module provided by IBM solutions team `https://github.com/ibm-cloud-architecture/terraform-icp-azure/tree/master/templates/icp-ce`.

Once the cluster was up,ran the `dig` command on the master and it worked. Running the `dig` command on the worker nodes resulted in failure. Any help to debug to the issue is much appreciated.

**Comment by eembsen** [comment]
I am running the latest Kubernetes on Ubuntu 18.04 nodes:

```
root@master03:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
After creating a small k8s cluster with one master and one worker I install calico using the command:

```
kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml
```

As a result of this installation I see a lot of new iptables entries but above all, DNS lookup stops working :-( rendering my nodes useless. Why?
