### ISSUE TITLE
About "No timeout when cni call cni binary file" in cni

### ISSUE THREAD

**Issue by jianzi123** [projectcalico/cni-plugin#615]
I found this is a bug fix about that no timeout when cni call cni binary file in `https://github.com/containernetworking/cni(https://github.com/containernetworking/cni/pull/568)`, I want to know how I could use the new func in calico-cni.

**Comment by caseydavenport** [comment]
@jianzi123 that PR is actually adding functionality to CNI runtimes - e.g. kubernetes - which call the Calico CNI plugin, and won't impact the Calico code itself. That fix will need to be pulled into k8s in order to be used.

Note that Calico v3.2.2 included a fix to the Calico plugin to timeout a particular call to the kernel which could hang due to a number of kernel bugs: https://github.com/projectcalico/cni-plugin/releases/tag/v3.2.2
